version: '2'
networks:
    default:
        external:
            name: kong-net
services:
  kong-database:  
    image: postgres:10.1
    container_name: kong-db-master
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - PGDATA=/data/docker/pgsql
    volumes:
      - /data/docker/pgsql/master:/data/docker/pgsql
    ports:
      - '5432:5432'
  kong:
    image:  kong:0.14.0
    container_name: kong
    ports:
      - '8000:8000'
      - '18443:8443'
      - '8001:8001'
      - '8444:8444'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    command:
      - /bin/sh
      - -c 
      - /docker-entrypoint.sh kong migrations up && /docker-entrypoint.sh kong docker-start
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga
    container_name: konga
    ports:
      - '1337:1337'    
    environment:
      - DB_ADAPTER=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=konga_database
    depends_on:
      - kong




